# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MedirDistanciaEntre
                                 A QGIS plugin
 Plugin para medir la distancia mínima entre dos entidades.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-05-01
        copyright            : (C) 2022 by José A. Pérez Casares
        email                : jperezcasares_at_gmail_com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MedirDistanciaEntre class from file MedirDistanciaEntre.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .medir_distancia_entre import MedirDistanciaEntre
    return MedirDistanciaEntre(iface)
